//h-2
var allAnswers = [
  { romaji: "tsukue", jpg: "つくえ / 机", indo: "meja" },
  { romaji: "isu", jpg: "いす / 椅子", indo: "kursi" },
  { romaji: "tana", jpg: "たな / 田な", indo: "ladang" },
  { romaji: "tana", jpg: "たな / 棚", indo: "lemari" },
  { romaji: "tana", jpg: "たな / 種", indo: "benih atau jenis" },
  { romaji: "terebi", jpg: "テレビ", indo: "televisi" },
  { romaji: "reizouko", jpg: "れいぞうこ / 冷蔵庫", indo: "kulkas" },
  { romaji: "sentakuki /sentakki", jpg: "せんたくき / 洗濯機", indo: "mesin cuci" },
  { romaji: "kagami", jpg: "かがみ / 鏡", indo: "cermin" },
  { romaji: "beddo / shindai", jpg: "ベッド / 寝台", indo: "tempat tidur" },
  { romaji: "nichi", jpg: "にち / 日", indo: "hari" },
  { romaji: "ito", jpg: "いと / 糸", indo: "benang / serat" },
  { romaji: "tsuki", jpg: "つき / 月", indo: "bulan" },
  { romaji: "toshi", jpg: "とし / 年", indo: "tahun" },
  { romaji: "doa / dooru / tobira", jpg: "どあ / ドア / (とびら / 扉)", indo: "pintu" },
  { romaji: "mado", jpg: "まど / 窓", indo: "jendela" },
  { romaji: "curtain / katen", jpg: "カーテン / かてん ", indo: "tirai" },
  { romaji: "garasu", jpg: "ガラス / がらす", indo: "kaca" },
  { romaji: "hon", jpg: "ほん / 本", indo: "buku" },
  { romaji: "borupen", jpg: "ボールペン / ぼーるぺん", indo: "pulpen" },
  { romaji: "Enpitsu", jpg: "えんぴつ / 鉛筆", indo: "pensil" },
  { romaji: "keshigomu", jpg: "けしゴム / 消しゴム", indo: "penghapus" },
  { romaji: "beddo", jpg: "ベッド / べっど", indo: "Kasur" },
  { romaji: "koe", jpg: "こえ / 声", indo: "suara" },
  { romaji: "ai", jpg: "あい / 愛", indo: "cinta" },
  { romaji: "yama", jpg: "やま / 山", indo: "gunung" },
  { romaji: "ue", jpg: "うえ / 上", indo: "atas" },
  { romaji: "shita", jpg: "した / 下", indo: "bawah" },
  { romaji: "jouzu", jpg: "じょうず / 上手", indo: "mahir / bagus" },
  { romaji: "nani", jpg: "なに / 何", indo: "apa?" },
  { romaji: "kawaii", jpg: "かわいい / 可愛い", indo: "lucu / manis" },
  { romaji: "tanoshii", jpg: "たのしい / 楽しい", indo: "menyenangkan" },
  { romaji: "uta", jpg: "うた / 歌", indo: "lagu" },
  { romaji: "minna-san", jpg: "みんなさん", indo: "semua orang" },
  { romaji: "ki", jpg: "き / 木", indo: "pohon" },
  { romaji: "hi", jpg: "ひ / 火", indo: "api" },
  { romaji: "kaze", jpg: "かぜ / 風", indo: "angin" },
  { romaji: "Bitto", jpg: "ビット", indo: "bit (dalam teknis komputer)" },
  { romaji: "shiawase na", jpg: "しあわせな / 幸せな", indo: "bahagia" },
  { romaji: "hi jou ni", jpg: "ひじょうに / 非常に", indo: "sangat / teramat" },
  { romaji: "sonota", jpg: "そのた / その他", indo: "lainnya / yang lain" },
  { romaji: "miru", jpg: "みる / 見る", indo: "melihat" },
  { romaji: "mieru", jpg: "みえる / 見える", indo: "terlihat / dapat dilihat" },
  { romaji: "sensei", jpg: "せんせい / 先生", indo: "guru / pengajar" },
  { romaji: "kaeru", jpg: "かえる / 変える", indo: "mengubah / mengganti" },
  { romaji: "hayai", jpg: "はやい / 早い", indo: "cepat" },
  { romaji: "tatakai", jpg: "たたかい / 戦い", indo: "pertempuran / perjuangan" },
  { romaji: "yawarageru", jpg: "やわらげる / 和らげる", indo: "meringankan / mengurangi" },
  { romaji: "hiku", jpg: "ひく / 引く (konteks umum)", indo: "menarik / mengeluarkan (konteks umum)" },
  { romaji: "hiku", jpg: "ひく / 引く (konteks musik)", indo: "memainkan / memetik (konteks musik)" },
  { romaji: "kau", jpg: "かう / 買う", indo: "membeli" },
];
