//h-2
var allAnswers = [
  { romaji: "tsukue", jpg: "つくえ / 机", indo: "meja" },
  { romaji: "isu", jpg: "いす / 椅子", indo: "kursi" },
  { romaji: "tana", jpg: "たな / 田な", indo: "ladang" },
  { romaji: "tana", jpg: "たな / 棚", indo: "lemari" },
  { romaji: "tana", jpg: "たな / 種", indo: "benih atau jenis" },
  { romaji: "terebi", jpg: "テレビ", indo: "televisi" },
  { romaji: "reizouko", jpg: "れいぞうこ / 冷蔵庫", indo: "kulkas" },
  { romaji: "sentakuki /sentakki", jpg: "せんたくき / 洗濯機", indo: "mesin cuci" },
  { romaji: "kagami", jpg: "かがみ / 鏡", indo: "cermin" },
  { romaji: "beddo / shindai", jpg: "ベッド / 寝台", indo: "tempat tidur" },
  { romaji: "nichi", jpg: "にち / 日", indo: "hari" },
  { romaji: "ito", jpg: "いと / 糸", indo: "benang / serat" },
  { romaji: "tsuki", jpg: "つき / 月", indo: "bulan" },
  { romaji: "toshi", jpg: "とし / 年", indo: "tahun" },
  { romaji: "doa / dooru / tobira", jpg: "どあ / ドア / (とびら / 扉)", indo: "pintu" },
  { romaji: "mado", jpg: "まど / 窓", indo: "jendela" },
  { romaji: "curtain / katen", jpg: "カーテン / かてん ", indo: "tirai" },
  { romaji: "garasu", jpg: "ガラス / がらす", indo: "kaca" },
  { romaji: "hon", jpg: "ほん / 本", indo: "buku" },
  { romaji: "borupen", jpg: "ボールペン / ぼーるぺん", indo: "pulpen" },
  { romaji: "Enpitsu", jpg: "えんぴつ / 鉛筆", indo: "pensil" },
  { romaji: "keshigomu", jpg: "けしゴム / 消しゴム", indo: "penghapus" },
  { romaji: "beddo", jpg: "ベッド / べっど", indo: "Kasur" },
];
